#!/bin/bash
# ----------------------------------------------------------------------
# Copyright (c) 20121 astrorafael@gmail.com.
#
# See the LICENSE file for details
# ----------------------------------------------------------------------
python -m tdbgaps -c -d $HOME/zptess/zptess.db -l $HOME/zptess/zptool.log $*
